package com.sztvis.datacenter.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sztvis.datacenter.db.OfflineData;

import com.sztvis.datacenter.db.OfflineDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig offlineDataDaoConfig;

    private final OfflineDataDao offlineDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        offlineDataDaoConfig = daoConfigMap.get(OfflineDataDao.class).clone();
        offlineDataDaoConfig.initIdentityScope(type);

        offlineDataDao = new OfflineDataDao(offlineDataDaoConfig, this);

        registerDao(OfflineData.class, offlineDataDao);
    }
    
    public void clear() {
        offlineDataDaoConfig.clearIdentityScope();
    }

    public OfflineDataDao getOfflineDataDao() {
        return offlineDataDao;
    }

}
